import { useEffect, useState, type FormEvent } from "react";
import { Building2, Loader2 } from "lucide-react";
import { AppLayout } from "../components/layout/AppLayout";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { CustomSelect } from "../components/ui/CustomSelect";
import { request, ApiError, NetworkError } from "../api/apiClient";
import { useToast } from "../hooks/useToast";

type Company = { id: string; name: string; pieceworkDistributionMode: "Manual" | "EqualAmongContributors" | "ProportionalToHours"; latenessGraceMinutes: number; latenessNotifyThresholdMinutes: number; payrollPeriodType: "Monthly" | "SemiMonthly"; defaultCurrency: string };
function message(error: unknown) { return error instanceof NetworkError ? "Нет подключения к серверу" : error instanceof ApiError ? error.message : "Не удалось сохранить настройки"; }
export default function SettingsPage() {
  const { showToast } = useToast(); const [company, setCompany] = useState<Company | null>(null); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { setError(""); try { setCompany(await request<Company>("/api/v1/companies/current")); } catch (cause) { setError(message(cause)); } }
  useEffect(() => { void load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); if (!company || saving) return; setSaving(true); setError(""); try { const updated = await request<Company>("/api/v1/companies/current", { method: "PUT", body: { pieceworkDistributionMode: company.pieceworkDistributionMode, latenessGraceMinutes: Number(company.latenessGraceMinutes), latenessNotifyThresholdMinutes: Number(company.latenessNotifyThresholdMinutes), payrollPeriodType: company.payrollPeriodType, defaultCurrency: company.defaultCurrency } }); setCompany(updated); showToast("Настройки компании сохранены"); } catch (cause) { setError(message(cause)); } finally { setSaving(false); } }
  return <AppLayout title="Настройки компании" subtitle="Настройки, поддерживаемые сервером">{!company ? <Card>{error ? <><p className="text-red">{error}</p><Button className="mt-3" size="sm" onClick={() => void load()}>Повторить</Button></> : <Loader2 className="animate-spin" />}</Card> : <Card className="max-w-2xl p-5"><form className="users-modal-form" onSubmit={submit}><h2 className="flex items-center gap-2 text-lg font-bold"><Building2 />{company.name}</h2><label><span>Распределение сдельной оплаты</span><CustomSelect fullWidth value={company.pieceworkDistributionMode} onValueChange={(pieceworkDistributionMode) => setCompany({ ...company, pieceworkDistributionMode: pieceworkDistributionMode as Company["pieceworkDistributionMode"] })} options={[{ value: "Manual", label: "Вручную" }, { value: "EqualAmongContributors", label: "Поровну" }, { value: "ProportionalToHours", label: "По часам" }]} /></label><label><span>Льготный период опоздания, мин.</span><input type="number" min="0" value={company.latenessGraceMinutes} onChange={(e) => setCompany({ ...company, latenessGraceMinutes: Number(e.target.value) })} /></label><label><span>Порог уведомления об опоздании, мин.</span><input type="number" min="0" value={company.latenessNotifyThresholdMinutes} onChange={(e) => setCompany({ ...company, latenessNotifyThresholdMinutes: Number(e.target.value) })} /></label><label><span>Период зарплаты</span><CustomSelect fullWidth value={company.payrollPeriodType} onValueChange={(payrollPeriodType) => setCompany({ ...company, payrollPeriodType: payrollPeriodType as Company["payrollPeriodType"] })} options={[{ value: "Monthly", label: "Ежемесячно" }, { value: "SemiMonthly", label: "Дважды в месяц" }]} /></label><label><span>Валюта</span><input maxLength={3} value={company.defaultCurrency} onChange={(e) => setCompany({ ...company, defaultCurrency: e.target.value.toUpperCase() })} /></label>{error && <p className="users-modal-error">{error}</p>}<Button type="submit" disabled={saving}>{saving ? "Сохранение…" : "Сохранить"}</Button></form></Card>}</AppLayout>;
}