/**
 * Maps a person's full name to a real headshot photo under public/images/people/.
 * Avatar falls back to the initials circle automatically if a name has no entry
 * here, or if the image fails to load — so this map can be filled in incrementally.
 */
export const PERSON_PHOTOS: Record<string, string> = {
  "Фируз Рахмонов": "/images/people/firuz-rakhmonov.jpg",
  "Комрон Саидов": "/images/people/komron-saidov.jpg",
  "Шариф Давлатов": "/images/people/sharif-davlatov.jpg",
  "Мухиддин Холов": "/images/people/mukhiddin-kholov.jpg",
  "Мирзоев Шахром": "/images/people/mirzoev-shakhrom.jpg",
  "Абдуллоев Бахтиёр": "/images/people/abdulloev-bakhtiyor.jpg",
  "Юсупов Далер": "/images/people/yusupov-daler.jpg",
  "Нозим Икромов": "/images/people/nozim-ikromov.jpg",
  "Рустамов Комрон": "/images/people/rustamov-komron.jpg",
  "Темуров Фируз": "/images/people/temurov-firuz.jpg",
  "Каримов Сухроб": "/images/people/karimov-sukhrob.jpg",
  "Мехринисо Каримова": "/images/people/mekhriniso-karimova.jpg",
  "Азизбек Юсупов": "/images/people/azizbek-yusupov.jpg",
  "Абдулло Мирзоев": "/images/people/abdullo-mirzoev.jpg",
  "Бахтиёр Курбонов": "/images/people/bakhtier-kurbonov.jpg",
  "Наим Сафаров": "/images/people/naim-safarov.jpg",
  "Далер Хамидов": "/images/people/daler-khamidov.jpg",
  "Хуршед Назаров": "/images/people/khurshed-nazarov.jpg",
  "Гулмурод Шарипов": "/images/people/gulmurod-sharipov.jpg",
  "Зафар Одинаев": "/images/people/zafar-odinaev.jpg",
  "Рустам Каримов": "/images/people/rustam-karimov.jpg",
  "Далер Юсупов": "/images/people/daler-yusupov.jpg",
  "Рахим Назаров": "/images/people/rakhim-nazarov.jpg",
  "Рустам Саидов": "/images/people/rustam-saidov.jpg",
  "Комрон Набиев": "/images/people/komron-nabiev.jpg",
  "Исмоилов Рахим": "/images/people/ismoilov-rakhim.jpg",
  "Хасанов Саид": "/images/people/khasanov-said.jpg",
  "Пулатов Абдували": "/images/people/pulatov-abduvali.jpg",
  "Тошев Нуриддин": "/images/people/toshev-nuriddin.jpg",
  "Мирзораимов Файзулло": "/images/people/mirzoraimov-fayzullo.jpg",
  "Рахматов Гайрат": "/images/people/rakhmatov-gayrat.jpg",
  "Юсуфов Максуд": "/images/people/yusufov-maksud.jpg",
  "Назаров Собир": "/images/people/nazarov-sobir.jpg",
  "Собиров Толиб": "/images/people/sobirov-tolib.jpg",
  "Джураев Ражаб": "/images/people/dzhuraev-razhab.jpg",
  "Ниязов Икром": "/images/people/niyazov-ikrom.jpg",
  "Раджабов Хикмат": "/images/people/radzhabov-khikmat.jpg",
  "Хамидов Латиф": "/images/people/khamidov-latif.jpg",
  "Шарипов Мансур": "/images/people/sharipov-mansur.jpg",
  "Умаров Одил": "/images/people/umarov-odil.jpg",
  "Салимов Джалол": "/images/people/salimov-dzhalol.jpg",
  "Сафаров Бободжон": "/images/people/safarov-bobodzhon.jpg",
  "Абдуллаев Курбон": "/images/people/abdullaev-kurbon.jpg",
  "Латипов Сафар": "/images/people/latipov-safar.jpg",
  "Норов Эмом": "/images/people/norov-emom.jpg",
  "Юлдашев Азиз": "/images/people/yuldashev-aziz.jpg",
  "Файзуллоев Фаррух": "/images/people/fayzulloev-farrukh.jpg",
  "Ахмедов Бехруз": "/images/people/akhmedov-bekhruz.jpg",
  "Валиев Джамшед": "/images/people/valiev-dzhamshed.jpg",
  "Каримов Тимур": "/images/people/karimov-timur.jpg",
  "Курбонов Наим": "/images/people/kurbonov-naim.jpg",
  "Гуломов Хуршед": "/images/people/gulomov-khurshed.jpg",
  "Бердиев Сино": "/images/people/berdiev-sino.jpg",
  "Эргашев Умед": "/images/people/ergashev-umed.jpg",
  "Одинаев Далер": "/images/people/odinaev-daler.jpg",
  "Исмоилов Шерали": "/images/people/ismoilov-sherali.jpg",
  "Хасанов Отабек": "/images/people/khasanov-otabek.jpg",
  "Пулатов Санжар": "/images/people/pulatov-sanzhar.jpg",
  "Тошев Диловар": "/images/people/toshev-dilovar.jpg",
  "Мирзораимов Парвиз": "/images/people/mirzoraimov-parviz.jpg",
  "Рахматов Восид": "/images/people/rakhmatov-vosid.jpg",
  "Юсуфов Акбар": "/images/people/yusufov-akbar.jpg",
  "Назаров Хумоюн": "/images/people/nazarov-khumoyun.jpg",
  "Собиров Зохир": "/images/people/sobirov-zokhir.jpg",
  "Джураев Исмоил": "/images/people/dzhuraev-ismoil.jpg",
  "Ниязов Рахим": "/images/people/niyazov-rakhim.jpg",
  "Раджабов Саид": "/images/people/radzhabov-said.jpg",
  "Хамидов Абдували": "/images/people/khamidov-abduvali.jpg",
  "Шарипов Нуриддин": "/images/people/sharipov-nuriddin.jpg",
  "Умаров Файзулло": "/images/people/umarov-fayzullo.jpg",
  "Салимов Гайрат": "/images/people/salimov-gayrat.jpg",
  "Сафаров Максуд": "/images/people/safarov-maksud.jpg",
  "Абдуллаев Собир": "/images/people/abdullaev-sobir.jpg",
  "Латипов Толиб": "/images/people/latipov-tolib.jpg",
  "Норов Ражаб": "/images/people/norov-razhab.jpg",
  "Юлдашев Икром": "/images/people/yuldashev-ikrom.jpg",
  "Файзуллоев Хикмат": "/images/people/fayzulloev-khikmat.jpg",
  "Ахмедов Латиф": "/images/people/akhmedov-latif.jpg",
  "Валиев Мансур": "/images/people/valiev-mansur.jpg",
  "Каримов Одил": "/images/people/karimov-odil.jpg",
  "Курбонов Джалол": "/images/people/kurbonov-dzhalol.jpg",
  "Гуломов Бободжон": "/images/people/gulomov-bobodzhon.jpg",
  "Бердиев Курбон": "/images/people/berdiev-kurbon.jpg",
  "Эргашев Сафар": "/images/people/ergashev-safar.jpg",
  "Одинаев Эмом": "/images/people/odinaev-emom.jpg",
  "Исмоилов Азиз": "/images/people/ismoilov-aziz.jpg",
  "Хасанов Фаррух": "/images/people/khasanov-farrukh.jpg",
  "Пулатов Бехруз": "/images/people/pulatov-bekhruz.jpg",
  "Тошев Джамшед": "/images/people/toshev-dzhamshed.jpg",
  "Мирзораимов Тимур": "/images/people/mirzoraimov-timur.jpg",
  "Рахматов Наим": "/images/people/rakhmatov-naim.jpg",
  "Юсуфов Хуршед": "/images/people/yusufov-khurshed.jpg",
  "Назаров Сино": "/images/people/nazarov-sino.jpg",
  "Собиров Умед": "/images/people/sobirov-umed.jpg",
  "Джураев Далер": "/images/people/dzhuraev-daler.jpg",
  "Ниязов Шерали": "/images/people/niyazov-sherali.jpg",
  "Раджабов Отабек": "/images/people/radzhabov-otabek.jpg",
  "Хамидов Санжар": "/images/people/khamidov-sanzhar.jpg",
  "Шарипов Диловар": "/images/people/sharipov-dilovar.jpg",
  "Умаров Парвиз": "/images/people/umarov-parviz.jpg",
  "Салимов Восид": "/images/people/salimov-vosid.jpg",
  "Баходур Раджабов": "/images/people/bakhodur-radzhabov.jpg",
  "Вафо Раджабов": "/images/people/vafo-radzhabov.jpg",
  "Гайрат Раджабов": "/images/people/gayrat-radzhabov.jpg",
  "Джамшед Раджабов": "/images/people/dzhamshed-radzhabov.jpg",
  "Еркин Раджабов": "/images/people/erkin-radzhabov.jpg",
  "Жасур Раджабов": "/images/people/zhasur-radzhabov.jpg",
  "Зохир Раджабов": "/images/people/zokhir-radzhabov.jpg",
  "Икром Раджабов": "/images/people/ikrom-radzhabov.jpg",
  "Камол Раджабов": "/images/people/kamol-radzhabov.jpg",
  "Мансур Раджабов": "/images/people/mansur-radzhabov.jpg",
  "Наим Раджабов": "/images/people/naim-radzhabov.jpg",
  "Олим Раджабов": "/images/people/olim-radzhabov.jpg",
  "Парвиз Раджабов": "/images/people/parviz-radzhabov.jpg",
  "Равшан Раджабов": "/images/people/ravshan-radzhabov.jpg",
  "Сино Раджабов": "/images/people/sino-radzhabov.jpg",
  "Толиб Раджабов": "/images/people/tolib-radzhabov.jpg",
  "Умед Раджабов": "/images/people/umed-radzhabov.jpg",
  "Фарход Раджабов": "/images/people/farkhod-radzhabov.jpg",
  "Хуршед Раджабов": "/images/people/khurshed-radzhabov.jpg",
  "Шодмон Раджабов": "/images/people/shodmon-radzhabov.jpg",
  "Эмом Раджабов": "/images/people/emom-radzhabov.jpg",
  "Юнус Раджабов": "/images/people/yunus-radzhabov.jpg",
  "Якуб Раджабов": "/images/people/yakub-radzhabov.jpg",
  "Бехруз Раджабов": "/images/people/bekhruz-radzhabov.jpg",
  "Диловар Раджабов": "/images/people/dilovar-radzhabov.jpg",
  "Исфандиёр Раджабов": "/images/people/isfandier-radzhabov.jpg",
  "Каримджон Раджабов": "/images/people/karimdzhon-radzhabov.jpg",
  "Нусрат Раджабов": "/images/people/nusrat-radzhabov.jpg",
  "Азиз Назаров": "/images/people/aziz-nazarov.jpg",
  "Баходур Назаров": "/images/people/bakhodur-nazarov.jpg",
  "Вафо Назаров": "/images/people/vafo-nazarov.jpg",
  "Гайрат Назаров": "/images/people/gayrat-nazarov.jpg",
  "Джамшед Назаров": "/images/people/dzhamshed-nazarov.jpg",
  "Еркин Назаров": "/images/people/erkin-nazarov.jpg",
};

/**
 * Some datasets reference the same real person by an abbreviated form
 * ("Ф. Рахмонов" instead of "Фируз Рахмонов"). Resolves a display name to a
 * photo by trying an exact match first, then a "first-initial + surname" match
 * against PERSON_PHOTOS, so the same person's photo shows up consistently
 * everywhere they appear — without renaming the underlying data.
 */
export function resolvePersonPhoto(name: string): string | undefined {
  if (PERSON_PHOTOS[name]) return PERSON_PHOTOS[name];

  const abbreviated = name.match(/^([А-ЯЁ])\.\s*(.+)$/);
  if (!abbreviated) return undefined;

  const [, initial, surname] = abbreviated;
  const match = Object.keys(PERSON_PHOTOS).find((fullName) => {
    const [firstName, lastName] = fullName.split(" ");
    return lastName === surname && firstName?.startsWith(initial);
  });
  return match ? PERSON_PHOTOS[match] : undefined;
}
